### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by MrDr-Pan** [ziraax/timesfm_torch#1]
Thanks for sharing the codes!
This error seems to be caused by a mismatch in the size of the output of the model and the predict target. How can I modify it?
“RuntimeError: The expanded size of the tensor (50) must match the existing size (32) at non-singleton dimension 1.  Target sizes: [-1, 50, -1].  Tensor sizes: [32, 1]RuntimeError: The expanded size of the tensor (50) must match the existing size (32) at non-singleton dimension 1.  Target sizes: [-1, 50, -1].  Tensor sizes: [32, 1]”

**Comment by ziraax** [comment]
Hello!

I'm still working on this issue. I will get back to you soon or commit a fix to the codebase as soon as possible.

Note: This repository is a side project. Although I plan to fully implement the model, there might be misconceptions as I'm still fairly new to PyTorch.

**Comment by MrDr-Pan** [comment]
> Hello!
> 
> I'm still working on this issue. I will get back to you soon or commit a fix to the codebase as soon as possible.
> 
> Note: This repository is a side project. Although I plan to fully implement the model, there might be misconceptions as I'm still fairly new to PyTorch.

Thanks for your reply. I guess the reason for the error is in the function “create_sequence_windows”，which is a little confusing.

**Comment by ziraax** [comment]
Issue should be fixed, even thought there still may be flaws on the implementation, it's now training on synthetical data.

**Comment by ziraax** [comment]
Error was indead coming from the create_sequence_windows function

**Comment by MrDr-Pan** [comment]
Thank you for your reply and the code can be indeed run now. I wish your PyTorch skills can be as good as your Java skills in the near future. And, happy coding!



> Issue should be fixed, even thought there still may be flaws on the implementation, it's now training on synthetical data.

**Comment by ziraax** [comment]
Hahaha on my way!
